# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search = QtWidgets.QLabel(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(40, 50, 291, 31))
        self.search.setObjectName("search")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(340, 50, 361, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.find_creature = QtWidgets.QLabel(self.centralwidget)
        self.find_creature.setGeometry(QtCore.QRect(200, 150, 381, 31))
        self.find_creature.setObjectName("find_creature")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 259, 761, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.MapButtons = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.MapButtons.setContentsMargins(0, 0, 0, 0)
        self.MapButtons.setObjectName("MapButtons")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(340, 480, 131, 31))
        self.exit.setObjectName("exit")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(710, 52, 75, 31))
        self.search_btn.setObjectName("search_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Поиск существа по названию/параметру:</span></p></body></html>"))
        self.find_creature.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Найти существо самостоятельно на одной из карт:</span></p></body></html>"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.search_btn.setText(_translate("MainWindow", "Найти"))
